function artemis_mission_data_explorer()
% ARTEMIS_MISSION_DATA_EXPLORER
% A simple MATLAB menu-based tool that makes Artemis mission information
% easier for the general public to explore and understand.
% Made by: Yassin Elhadidi and Laney Fagerstrom

    clc;
    close all;

    missionData = buildMissionData();

    keepRunning = true;
    while keepRunning
        choice = menu( ...
            'Artemis Mission Data Explorer', ...
            'Artemis I Overview', ...
            'Artemis II Overview', ...
            'Why Lunar Missions Matter', ...
            'Entire Artemis Program Explained', ...
            'Mission Timeline Visualization', ...
            'Open Artemis News', ...
            'Open NASA Gallery', ...
            'Exit');

        switch choice
            case 1
                showMissionSummary(missionData(1));
            case 2
                showMissionSummary(missionData(2));
            case 3
                showWhyLunarMissions();
            case 4
                showEntireArtemisExplanation(missionData);
            case 5
                showTimelineVisualization(missionData);
            case 6
                openWebsite('https://www.nasa.gov/humans-in-space/artemis/');
            case 7
                openWebsite('https://images.nasa.gov/');
            otherwise
                keepRunning = false;
                msgbox( ...
                    sprintf(['Thank you for using Artemis Mission Data Explorer.\n\n' ...
                    'Created by Yassin Elhadidi and Delaney Fagerstrom.']), ...
                    'Goodbye');
        end
    end
end

function missionData = buildMissionData()
    missionData(1).name = 'Artemis I';
    missionData(1).missionType = 'Uncrewed lunar test flight';
    missionData(1).agency = 'NASA';
    missionData(1).spacecraft = 'Orion';
    missionData(1).rocket = 'Space Launch System (SLS)';
    missionData(1).crewSize = 0;
    missionData(1).launchYear = 2022;
    missionData(1).status = 'Completed';
    missionData(1).primaryGoal = 'Test Orion and SLS together in deep space before sending astronauts.';
    missionData(1).trajectory = 'Earth launch -> Moon orbit path -> deep-space travel -> return to Earth';
    missionData(1).summary = [ ...
        'Artemis I was the first mission in NASA''s Artemis program and it flew without a crew. ' ...
        'Its main purpose was to test the Orion spacecraft and the Space Launch System rocket in a real deep-space mission. ' ...
        'The spacecraft traveled around the Moon and then returned safely to Earth. ' ...
        'This mission helped NASA confirm that the systems needed for future astronaut missions can work in space.'];
    missionData(1).importance = [ ...
        'Artemis I was important because it was the first major test of the Artemis system. ' ...
        'It reduced risk for future crewed flights and provided data about spacecraft performance, heat shielding, communication, and navigation.'];

    missionData(2).name = 'Artemis II';
    missionData(2).missionType = 'Crewed lunar flyby (no landing)';
    missionData(2).agency = 'NASA';
    missionData(2).spacecraft = 'Orion';
    missionData(2).rocket = 'Space Launch System (SLS)';
    missionData(2).crewSize = 4;
    missionData(2).launchYear = 2026;
    missionData(2).status = 'Planned';
    missionData(2).primaryGoal = 'Test human deep-space travel systems with astronauts on board.';
    missionData(2).trajectory = 'Earth orbit -> Moon flyby -> return to Earth';
    missionData(2).summary = [ ...
        'Artemis II is NASA''s first crewed mission in the Artemis program and a major step toward returning humans to the Moon. ' ...
        'Four astronauts will travel aboard the Orion spacecraft, launched by the Space Launch System rocket, and perform a flyby of the Moon before returning to Earth. ' ...
        'The mission does not include a lunar landing. ' ...
        'Instead, it is designed to test life support, navigation, and deep-space operations with a human crew on board.'];
    missionData(2).importance = [ ...
        'Artemis II is historically significant because it will be the first crewed mission beyond low Earth orbit since the Apollo era. ' ...
        'It helps prove that NASA can safely send astronauts far from Earth again, which is necessary before future Moon landings and long-term missions to Mars.'];

    missionData(3).name = 'Artemis III';
    missionData(3).missionType = 'Planned crewed lunar landing';
    missionData(3).agency = 'NASA';
    missionData(3).spacecraft = 'Orion and lunar landing systems';
    missionData(3).rocket = 'Space Launch System (SLS)';
    missionData(3).crewSize = 4;
    missionData(3).launchYear = 2026;
    missionData(3).status = 'Planned';
    missionData(3).primaryGoal = 'Land humans on the Moon and continue long-term lunar exploration.';
    missionData(3).trajectory = 'Earth launch -> lunar orbit -> crew landing on Moon -> return';
    missionData(3).summary = [ ...
        'Artemis III is planned as the mission that will return humans to the lunar surface. ' ...
        'It builds on lessons learned from Artemis I and Artemis II and is expected to mark a new era of exploration. ' ...
        'The mission supports NASA''s long-term goal of building experience for sustainable Moon missions and future journeys to Mars.'];
    missionData(3).importance = [ ...
        'Artemis III matters because it turns testing into action. ' ...
        'It is expected to expand science, inspire the public, and help create the systems and experience needed for long-term exploration beyond Earth.'];
end

function showMissionSummary(mission)
    details = sprintf([ ...
        '%s\n\n' ...
        'Mission Type: %s\n' ...
        'Agency: %s\n' ...
        'Spacecraft: %s\n' ...
        'Rocket: %s\n' ...
        'Crew Size: %d\n' ...
        'Planned/Launch Year: %d\n' ...
        'Status: %s\n' ...
        'Primary Goal: %s\n' ...
        'Trajectory: %s\n\n' ...
        'Simple Summary:\n%s\n\n' ...
        'Why It Matters:\n%s'], ...
        mission.name, ...
        mission.missionType, ...
        mission.agency, ...
        mission.spacecraft, ...
        mission.rocket, ...
        mission.crewSize, ...
        mission.launchYear, ...
        mission.status, ...
        mission.primaryGoal, ...
        mission.trajectory, ...
        mission.summary, ...
        mission.importance);

    helpdlg(details, mission.name);
end

function showWhyLunarMissions()
    message = sprintf([ ...
        'Why are lunar missions important?\n\n' ...
        '1. The Moon is a nearby testing ground for deep-space exploration.\n' ...
        '2. Lunar missions help engineers improve spacecraft, life support, and navigation systems.\n' ...
        '3. Scientists can study the Moon to learn more about the history of the solar system.\n' ...
        '4. NASA can practice long-term missions that may later support travel to Mars.\n' ...
        '5. These missions inspire public interest in science, technology, engineering, and math.\n\n' ...
        'In simple terms, going to the Moon helps humanity learn how to live, work, and explore farther from Earth.']);

    helpdlg(message, 'Why Lunar Missions Matter');
end

function showEntireArtemisExplanation(missionData)
    message = sprintf([ ...
        'The Artemis program is NASA''s modern plan to return humans to the Moon and prepare for future missions to Mars.\n\n' ...
        'Program Steps:\n' ...
        '1. Artemis I tested the Orion spacecraft and SLS rocket without astronauts.\n' ...
        '2. Artemis II will send astronauts around the Moon to test human deep-space travel.\n' ...
        '3. Artemis III is planned to land humans on the Moon.\n\n' ...
        'Main Goals:\n' ...
        '- Return humans to the Moon safely.\n' ...
        '- Build experience for sustainable lunar exploration.\n' ...
        '- Support scientific discoveries.\n' ...
        '- Inspire the public and future scientists.\n' ...
        '- Prepare for eventual human missions to Mars.\n\n' ...
        'Current Artemis Missions Included in This Tool:\n' ...
        '- %s\n' ...
        '- %s\n' ...
        '- %s'], ...
        missionData(1).name, missionData(2).name, missionData(3).name);

    helpdlg(message, 'Entire Artemis Program');
end

function showTimelineVisualization(missionData)
    years = [missionData.launchYear];
    crewSizes = [missionData.crewSize];
    labels = {missionData.name};

    figure('Name', 'Artemis Mission Timeline', 'NumberTitle', 'off', 'Color', 'w');

    subplot(2,1,1);
    stem(years, 1:numel(years), 'filled', 'LineWidth', 2);
    yticks(1:numel(labels));
    yticklabels(labels);
    xlabel('Year');
    ylabel('Mission Order');
    title('Artemis Mission Timeline');
    grid on;

    subplot(2,1,2);
    bar(crewSizes, 'FaceColor', [0.1 0.45 0.8]);
    xticks(1:numel(labels));
    xticklabels(labels);
    ylabel('Crew Size');
    title('Crew Size by Mission');
    grid on;
end

function openWebsite(url)
    try
        web(url, '-browser');
    catch
        errordlg(sprintf('Could not open the website automatically.\n\nURL: %s', url), ...
            'Browser Error');
    end
end
